version: "3"
services:
    auth_service:
        build: ./auth_service/
        environment:
            DB_USER: root
            DB_PASS: rootpassword
            DB_HOST: auth_storage
            DB_PORT: 27017
            PASSWORD_MIN_LENGTH: 8
            SALT_ROUNDS: 8
            TOKEN_EXPIRATION: 10
            JWT_SECRET: secret
        ports:
            - 8000:8000
        depends_on:
            - auth_storage
    auth_storage:
        image: mongo:latest
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: rootpassword
        command: mongod --quiet --logpath /dev/null
    paste_service:
        build: ./paste_service/
        environment:
            DB_USER: root
            DB_PASS: rootpassword
            DB_HOST: paste_storage
            DB_PORT: 27017
            PASTE_EXPIRATION: 5
            AUTH_SERVICE_HOST: auth_service
            AUTH_SERVICE_PORT: 8000
        ports:
            - 9000:9000
        depends_on:
            - paste_storage
    paste_storage:
        image: mongo:latest
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: rootpassword
        command: mongod --quiet --logpath /dev/null
    new_ui:
        build:
            context: ./new_ui/
            args:
                AUTH_SERVICE_HOST: localhost
                AUTH_SERVICE_PORT: 8000
                PASTE_SERVICE_HOST: localhost
                PASTE_SERVICE_PORT: 9000
        ports:
            - 3000:3000
        depends_on:
            - paste_service
            - auth_service
