services:
    auth_service:
        build:
            context: ./auth_service/
            target: development
        environment:
            DB_USER: root
            DB_PASS: rootpassword
            DB_HOST: auth_storage
            DB_PORT: 27017
            PASSWORD_MIN_LENGTH: 8
            SALT_ROUNDS: 8
            TOKEN_EXPIRATION: 10
            JWT_SECRET: secret
            RABBIT_MQ_USER: rabbitmq
            RABBIT_MQ_PASS: pass
            RABBIT_MQ_HOST: message_queue
            RABBIT_MQ_PORT: 5672
        volumes:
            - ./auth_service/app:/root/auth_service
        container_name: auth_service
        ports:
            - 8000:8000
        depends_on:
            auth_storage:
                condition: service_started
            message_queue:
                condition: service_healthy
    auth_storage:
        image: mongo:latest
        logging:
            driver: none
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: rootpassword
        command: mongod --quiet --logpath /dev/null
        container_name: auth_storage
        ports:
            - 27017:27017
    paste_service:
        build:
            context: ./paste_service/
            target: development
        environment:
            PASTE_EXPIRATION: 5
            AUTH_SERVICE_HOST: auth_service
            AUTH_SERVICE_PORT: 8000
            MYSQL_USER: dbuser
            MYSQL_PASSWORD: dbpassword
            MYSQL_HOST: paste_storage
            MYSQL_PORT: 3306
            MYSQL_DATABASE: shit_pasting
            PASTES_PAGE_SIZE: 10
        volumes:
            - ./paste_service/app:/root/paste_service
        container_name: paste_service
        ports:
            - 9000:9000
        depends_on:
            paste_storage:
                condition: service_healthy
    paste_storage:
        image: mysql:latest
        container_name: paste_storage
        logging:
            driver: none
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: shit_pasting
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: dbuser
            MYSQL_PASSWORD: dbpassword
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10
        volumes:
            - ./paste_storage_dump:/docker-entrypoint-initdb.d
    new_ui:
        build:
            context: ./new_ui/
            args:
                AUTH_SERVICE_HOST: localhost
                AUTH_SERVICE_PORT: 8000
                PASTE_SERVICE_HOST: localhost
                PASTE_SERVICE_PORT: 9000
        container_name: ui
        ports:
            - 3000:3000
        depends_on:
            - paste_service
            - auth_service
    message_queue:
        image: rabbitmq:3-management
        container_name: rabbitmq
        restart: always
        ports:
            - 5672:5672
            - 15672:15672
        environment:
            - RABBITMQ_DEFAULT_USER=rabbitmq
            - RABBITMQ_DEFAULT_PASS=pass
        healthcheck:
            test: rabbitmq-diagnostics -q check_running
            interval: 30s
            timeout: 30s
            retries: 5
