version: "3"
services:
    auth_service:
        build: ./auth_service/
        environment:
            DB_USER: root
            DB_PASS: rootpassword
            DB_HOST: auth_storage
            DB_PORT: 27017
            PASSWORD_MIN_LENGTH: 8
            SALT_ROUNDS: 8
            TOKEN_EXPIRATION: 10
            JWT_SECRET: secret
        ports:
            - 8000:8000
        depends_on:
            - auth_storage
    auth_storage:
        image: mongo:latest
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: rootpassword
    paste_service:
        build: ./paste_service/
        environment:
            DB_USER: root
            DB_PASS: rootpassword
            DB_HOST: paste_storage
            DB_PORT: 27017
            JWT_SECRET: secret
            PASTE_EXPIRATION: 5
        ports:
            - 9000:9000
        depends_on:
            - paste_storage
    paste_storage:
        image: mongo:latest
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ui:
        build: ./ui/
        ports:
            - 3000:3000
