version: "3"
services:
    auth_service:
        build: ./auth_service/
        environment:
            DB_USER: root
            DB_PASS: rootpassword
            DB_HOST: auth_storage
            DB_PORT: 27017
            PASSWORD_MIN_LENGTH: 8
            SALT_ROUNDS: 8
            TOKEN_EXPIRATION: 10
            JWT_SECRET: secret
        ports:
            - 8000:8000
        depends_on:
            - auth_storage
    auth_storage:
        image: mongo:latest
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: rootpassword
        ports:
            - 27017:27017
